version: '3.8'

services:
  web:
    build: .
    command: gunicorn Bunker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1

  redis:
    image: "redis:alpine"

volumes:
  static_volume:
  media_volume: