# Generated by Django 5.0.6 on 2024-06-06 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('body_build', models.CharField(blank=True, max_length=100)),
                ('a_human_trait', models.CharField(blank=True, max_length=100)),
                ('speciality', models.CharField(blank=True, max_length=100)),
                ('health', models.CharField(blank=True, max_length=100)),
                ('hobby', models.CharField(blank=True, max_length=100)),
                ('phobia', models.CharField(blank=True, max_length=100)),
                ('inventory', models.CharField(blank=True, max_length=100)),
                ('more_information', models.CharField(blank=True, max_length=100)),
                ('special_feature1', models.CharField(blank=True, max_length=100)),
                ('special_feature2', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to='main.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='main.room'),
        ),
    ]
