# Generated by Django 5.0.6 on 2024-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_room_cataclysm'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_game_started',
            field=models.BooleanField(default=False),
        ),
    ]
